### ISSUE TITLE
Revenue by company data legend wrong with commodity filter

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#1077]
wind ![image](https://user-images.githubusercontent.com/30806839/97359576-561d5280-1873-11eb-8026-45ad7ac6b1a5.png)
oil 
![image](https://user-images.githubusercontent.com/30806839/97359691-88c74b00-1873-11eb-87b7-14153016a0bc.png)

**Comment by mojobnichols** [comment]
Okay this is fixed -   The problem is that the summary couldn't take commodity and company into consideration.  I know calculate based on details returned.     The order is based on precalculation so for wind AVANGRID RENEWABLES LLC has more wind then EQUINOR ASA but it is in second  but EQUINOR ASA has more overall revenue.    The order should be off of calculated but that is a new issue, mostly this order is correct.
