### ISSUE TITLE
Refine display of grouping in the query tool

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#110]
Users are still having problems with this, so we need to review what we've already tried and come up with a new approach.

**Comment by mcharg** [comment]
What we've tried.

## Inline with filters
Users had difficulty with this, largely because they didn't know which drop-downs were and weren't filters.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/289e9715-34cf-41e4-9bef-1cbdb7c532f7)

## Change columns above table on right
The two participants who saw this version didn’t see the “Change columns” selector and didn’t get what it updated when they were shown what was in it.​
 ![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/ec96206c-021a-4175-8fcd-49249f1cd71e)

## Choose columns above table on left
* 5 participants saw this version and none of them noticed the option to choose columns.  ​
* Most understood what it did after opening the selector, but couldn’t articulate a better label.​
* We decided to try moving the filters out of the selector and relabeling them as “breakdowns” to see if that helped.​
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/977a55db-0ff6-4bbb-95fe-b81597fd3760) 

## Breakdowns on page
* This didn’t help at all.​
* Another factor that may be at play here is that there’s no column header on the Revenue Type column.  Several participants only noticed that it was broken out by Commodity.​
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/9ca97a4e-0e33-474e-94ea-6bf6b08c595d)

## Edit grouping button
* 6 participants were still confused by the grouping function, but thought it was useful once they understood. 
* Having to click on "group by" felt odd to some, but they couldn't come up with a better label.​
* Some thought it would be more like a pivot table.​
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/636907f0-3cba-42ca-8cbc-b1603a3699b9)
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/a6411bf4-0413-41a3-b74a-342ceeea3af6)

**Comment by mcharg** [comment]
@brentryanjohnson You had a suggestion for this a couple of weeks ago.  If you remember what that was, can you please document it here, so we don't forget what it was.

**Comment by brentryanjohnson** [comment]
@mcharg My suggestion was to eliminate the `EDIT GROUPING` button, eliminate the modal pop-up, and simply display the titles and drop-downs above the table, and then usability test the alternative.

Here's the rationale:

- Since there's been confusion around what "Grouping" means, it might help if the current grouping was exposed by default with the drop-down, instead of "hidden" by default behind the button/modal behavior. Theoretically, there would then be an immediate, on-screen relationship between the drop-down criteria and the tabular grouping.
- The button/modal requires an additional user interaction that might be unnecessary, given the limited options revealed.
- There's additional code activated by having another layer of user interaction with the modal (and another button) that may be unnecessary.

I don't know if this is the best solution or not. An alternative might be to keep exploring text alternatives, such as "Organize by." But I still think it might be more intuitive to expose the options immediately, even if the interface text is changed.

**Comment by mcharg** [comment]
Need to watch what we have in the new version in user interviews and then revisit.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/819b52fd-bafa-410e-9767-849717086095)

**Comment by mcharg** [comment]
This is still a major issue in the new design.  Will create new issues for specific fixes.
