### ISSUE TITLE
Explore Data: Determine approach for GOMESA data

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#131]
Ensure we have a place to put the GOMESA data in the new Explore Data design that we can link to from the annual press release that comes out before we have updated data in the spreadsheets.

**Comment by jennmalcolm** [comment]
Currently we have the state-level totals on the how it works GOMESA page, which we can keep but ideally won't since our content strategy is to have the data elsewhere. We then have the state and county level breakdowns on the state pages--which will be gone with the new explore data. So, we need to decide where and how to have the gomesa data. 

Here is a little background on how the process worked last year:

On the month that GOMESA disbursements are made to the states and counties, we receive a spreadsheet with just the GOMESA numbers from FM. This spreadsheet is not our normal disbursments spreadsheet. IT just has State, counties, and disbursements. We received a draft spreadsheet earlier this year, but we received the final numbers 3 days before the press release went out this year. We should have the GOMESA data published on NRRD as close as possible to the time that the press release goes out (requires coordination with the communications manager).

Then, the same numbers will be included in our normal monthly disbursements file, which we receive at the end of the month, the month following the disbursements. Currently this file is just going into the downloads and doesn't feed any features.

**Comment by mcharg** [comment]
@jennmalcolm I think it's too soon to add this to the next sprint.  We need to figure out what we're doing for disbursements overall first.

**Comment by jennmalcolm** [comment]
Our agreed upon will be to have a separate page and hard code the data each year for the press release). We decided integrating it into the explore data page presented too much of a content challenge due to the time period being different for that data than anything else we have (including the other disbursement data). We would like to have the ability to have a rolled up number for the state and counties within that state and expand for the number for that went directly to the state and the county details (accordian or something else MUI).

**Comment by mcharg** [comment]
I added #175 to design the stand alone page.
