### ISSUE TITLE
Review term "withheld" in relation to Native American data

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#1346]
We are using the term withheld for the Native American data on the download page, but the definition--citing the Trade Secrets Act--is not the reason that we do not publish Native American data. The withheld definition does say that we withhold all Native American location data without explaining why on that. In the query tool, we use the term "location not published." We should be consistent with our application of terms and make sure the glossary definition is appropriate for the Native American data and doesn't include extraneous info (e.g. Trade Secrets Act, 1 mine, 1 company).

![image](https://user-images.githubusercontent.com/30806839/107665277-4a576f80-6c5b-11eb-9881-06bd9db40333.png)
![image](https://user-images.githubusercontent.com/30806839/107665532-85f23980-6c5b-11eb-8a1d-04dd19804518.png)

**Comment by cthomasONRR** [comment]
@Maroyafaied @mcharg 

For this "withheld" issue, it seems like the definition just needs to be clarified... there are 3 possible scenarios as to why data is withheld:
 
First, data is withheld because it can be used to personally ID individuals. 
Second, because it is in violation of the Trade Secrets Act. 
Third, all Native American **location** data is withheld at all times. It's possible that other Native American data, aside from location, could fall into scenarios 1 and 2.

Maybe a simple clarification like I propose below could be implemented. The main point I am trying to make is that Native American data (aside from location) can potentially fall into the first two withheld scenarios the definition presents.

![image.png](https://images.zenhubusercontent.com/60f9807ebc2bf779cc3921f2/b6814936-c98a-4976-8021-6cb4034262a0)

**Comment by cthomasONRR** [comment]
This project is being closed- merged into #910
https://app.zenhub.com/workspaces/data-display-5464fa79c3cc8d7f4c384eaf/issues/onrr/onrr.gov-site/910
