### ISSUE TITLE
Update data pages on Wiki

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1526]
@Baymatt please add to the list if I missed anything

- [ ] https://github.com/ONRR/nrrd/wiki/Data-Types

**Comment by Baymatt** [comment]
Here is an updated version with outdated links replaced and years updated to reflect our data.
Q. Do we want to separate by fiscal and calendar year since the data are not on the same timelines?
Q. Do we want to combine revenue to reflect the new consolidated revenue page?


Type | Source | Commodities | Geography | Years
:--- | :----- | :---------- | :-------- | :----
[Production by Month](https://revenuedata.doi.gov/downloads/production-by-month/) | ONRR | oil, gas, coal | Federal and Native American | 2003-Most recent month
[Production by Fiscal & Calendar Year](https://revenuedata.doi.gov/downloads/production/) | ONRR | _all_ | Federal (states & counties) | 2003-2019
[Revenue by Month](https://revenuedata.doi.gov/downloads/revenue/) | ONRR | _all_ | Federal and Native American | 2003-Most recent month
[Revenue by Fiscal & Calendar Year](https://revenuedata.doi.gov/downloads/revenue/) | ONRR | _all_ | Federal (states & counties), Native American (without geography) | 2003-2020
[Federal Revenue by Company](https://revenuedata.doi.gov/downloads/federal-revenue-by-company/) | ONRR | _all_ | _N/A_ | 2013-2019
[Disbursements by Month](https://revenuedata.doi.gov/downloads/disbursements-by-month/) | ONRR | _all_ | States, counties (for geothermal)| October 2018-Most recent month
[Disbursements by Fiscal Year](https://revenuedata.doi.gov/downloads/disbursements/) |ONRR |_N/A_ | States | 2003-2020

**Comment by Maroyafaied** [comment]
@Baymatt Yes, let's separate out fiscal and calendar year. For revenue, let's not consolidate it but also list out each file and date, also can you change the geography for Revenue by month to say "Federal (states & counties), Native American (without geography)".  Thanks

**Comment by Baymatt** [comment]
Type | Source | Commodities | Geography | Years
:--- | :----- | :---------- | :-------- | :----
[Production by Month](https://revenuedata.doi.gov/downloads/production-by-month/) | ONRR | oil, gas, coal | Federal and Native American | 2003-Most recent month
[Production by Fiscal Year](https://revenuedata.doi.gov/downloads/production/) | ONRR | _all_ | Federal (states & counties) | 2003-2020
[Production by Calendar Year](https://revenuedata.doi.gov/downloads/production/) | ONRR | _all_ | Federal (states & counties) | 2003-2019
[Revenue by Month](https://revenuedata.doi.gov/downloads/revenue/) | ONRR | _all_ | Federal (states & counties), Native American (without geography) | 2003-Most recent month
[Revenue by Fiscal Year](https://revenuedata.doi.gov/downloads/revenue/) | ONRR | _all_ | Federal (states & counties), Native American (without geography) | 2003-2020
[Revenue by Calendar Year](https://revenuedata.doi.gov/downloads/revenue/) | ONRR | _all_ | Federal (states & counties), Native American (without geography) | 2003-2020
[Federal Revenue by Company](https://revenuedata.doi.gov/downloads/federal-revenue-by-company/) | ONRR | _all_ | _N/A_ | 2013-2019
[Disbursements by Month](https://revenuedata.doi.gov/downloads/disbursements-by-month/) | ONRR | _all_ | States, counties (for geothermal)| October 2018-Most recent month
[Disbursements by Fiscal Year](https://revenuedata.doi.gov/downloads/disbursements/) |ONRR |_N/A_ | States | 2003-2020

**Comment by Maroyafaied** [comment]
@Baymatt looks great!

**Comment by Baymatt** [comment]
@Maroyafaied Perfect, I'll go ahead and update the wiki page
