### ISSUE TITLE
Iterate homepage graphic design

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1586]

**Comment by mcharg** [comment]
See findings for what should be iterated: https://teams.microsoft.com/l/file/1F4C677A-4C50-4D72-83D8-561DBE560634?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=xlsx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FUser%20Research%2FStudies%2F38_HomepageGraphic%2FConsolidated%20Findings.xlsx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a

**Comment by arcasarana** [comment]
Document to edit the copy.  Shared on Teams. 

https://teams.microsoft.com/_#/docx/viewer/teams/https:~2F~2Fdoimspp.sharepoint.com~2Fsites~2FNRRD~2FShared%20Documents~2FGeneral~2Fonrr_homepage_graphic_content.docx?threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&messageId=-1&baseUrl=https:~2F~2Fdoimspp.sharepoint.com~2Fsites~2FNRRD&fileId=4f667b4c-babd-421a-9de1-449d07ee3166&ctx=chiclet&viewerAction=view

**Comment by CM805** [comment]
@arcasarana can you get a copy of the prototype as a PDF or screenshots.  I'd like to see how the content in the document provided related to what it looks like design-wise.  I did not save what you showed us at the intern meeting.

**Comment by arcasarana** [comment]
> @arcasarana can you get a copy of the prototype as a PDF or screenshots. I'd like to see how the content in the document provided related to what it looks like design-wise. I did not save what you showed us at the intern meeting.

@CM805 Sorry, Christa!  Just saw your message.  But here it is:

[https://xd.adobe.com/view/6b7d6581-992f-46a5-8d72-035d26beb875-3e2e/](url)

It's a clickable prototype.  On my laptop it's best viewed at 75% - otherwise, the text is a bit small.  Let me know if you make any changes to the Word Doc that you'd like reflected on the copy for the prototype.  The watermark for the last icon won't be there.

Also, here's a prototype of a single card with the slide up interaction that mimics Brandi's.  Not as smooth but this was requested a few weeks back.  For me, the button as it is (from the pattern library) doesn't read as slide up, but nevertheless...

[https://xd.adobe.com/view/3294ae3e-aa02-449e-bd53-90753ce42fbf-67c7/](url)

@Maroyafaied @mcharg @Baymatt @daniel-coleman-1

**Comment by mcharg** [comment]
@Maroyafaied Are you good with what's here?  If so, can we close this?
https://xd.adobe.com/view/6b7d6581-992f-46a5-8d72-035d26beb875-3e2e/

**Comment by Maroyafaied** [comment]
The design is good but I see a few content issues. Are we reviewing content in this issue or is there a separate issue for that?

**Comment by mcharg** [comment]
@Maroyafaied I think we have just the one issue.

The content may be updated in this doc.
https://teams.microsoft.com/_#/docx/viewer/teams/https:~2F~2Fdoimspp.sharepoint.com~2Fsites~2FNRRD~2FShared%20Documents~2FGeneral~2Fonrr_homepage_graphic_content.docx?threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&messageId=-1&baseUrl=https:~2F~2Fdoimspp.sharepoint.com~2Fsites~2FNRRD&fileId=4f667b4c-babd-421a-9de1-449d07ee3166&ctx=chiclet&viewerAction=view

**Comment by mcharg** [comment]
@Maroyafaied I created #1645 for next sprint to finalize content because there are several outstanding comments in the content doc.

**Comment by Maroyafaied** [comment]
@mcharg Ok I'll add my comments to that doc.
