### ISSUE TITLE
Add Federal Revenue by Company to the query tool

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/nrrd#159]
We're going to put this in the query tool as a separate data type instead of building a custom page.

**Comment by jennmalcolm** [comment]
We need to have this page under explore, not how it works, and it should work off the database data.

**Comment by mcharg** [comment]
Also need to put the data in the database.

**Comment by mcharg** [comment]
When we do this, we'll need to put the Revenue by Company link back on the homepage.

**Comment by mcharg** [comment]
@jennmalcolm @master12 Would it be easier to put revenue by company into the query tool than to build the separate page that we have on the site now?  I think it would serve the same user needs.

**Comment by mcharg** [comment]
Company could be an additional filter/column on the revenue data, but we would somehow have to mention that it's only available for CY.

**Comment by jennmalcolm** [comment]
It might be awkward trying to fit it in with the rest of revenue since there is no location data in that data set, but perhaps we can figure out a way to do it. If revenue by company were one of the main data set choices, that could work. Then different filters would be available.  I wouldn't want to lose the ability for people to explore/learn about this data (e.g. what the top companies are). Since the query tool is aimed at people who already know what data they want to see, I would like to see a circle chart or something else on explore data for the top companies. I know it could only show up for CY, but if we make that the default, that would work.

**Comment by mcharg** [comment]
I think it makes sense to have it as a separate data type in the query tool - I didn't even think about it not having location.  Just thinking that there's no particular reason to build the page we have now from scratch, if we can make it work within the query tool framework.  We have a horizontal bar chart visualization similar to the revenue summary for Explore Data that users loved when we tested it, but it might be nice to add a circle chart, as well.

**Comment by mcharg** [comment]
A circle chart may not work well, since we're limited to 6 color shades that can sort of be differentiated and "other" ends up huge with so many companies.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/329f8f4c-a895-4ee3-ae7b-0998d1fa73e5)

**Comment by mcharg** [comment]
Here's a first pass at design for putting revenue by company into the query tool.

The search companies field would work like the location search on Explore Data.  Default grouping would be by company with revenue type and commodity as the other options.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/295af6be-8727-4b2f-93d3-a9b70738d1d8)
