### ISSUE TITLE
Add Native American regulation to content guide

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1623]
In the content guide, explain why we use "Native American" and provide the regulation behind it.

**Comment by daniel-coleman-1** [comment]
https://www.congress.gov/bill/114th-congress/house-bill/4238/text

**Comment by Maroyafaied** [comment]
Move to NRRD and take it out of the onrr.gov content guide.

**Comment by daniel-coleman-1** [comment]
Ready for review @mcharg @Maroyafaied

**Comment by mcharg** [comment]
@daniel-coleman-1 Looks good.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 looks good.

**Comment by mcharg** [comment]
@Maroyafaied I fixed the link.

@daniel-coleman-1 You still say to use Native American on onrr.gov.  Please change it to something indicating that we use Indian on onrr.gov to be consistent with how ONRR uses it as an agency.

**Comment by daniel-coleman-1** [comment]
Updated:
![Screenshot 2021-07-27 152903](https://user-images.githubusercontent.com/83892362/127230249-eafa8770-5744-42a7-a304-66daf8c414f5.png)

**Comment by daniel-coleman-1** [comment]
I've been going back and fourth on this, we seem to be violating HR 4238 here:

![Screenshot 2021-07-27 153006](https://user-images.githubusercontent.com/83892362/127230361-3d336610-ad29-408a-bff6-e5d083b24a15.png)

![Screenshot 2021-07-27 153021](https://user-images.githubusercontent.com/83892362/127230379-6b8b85db-2264-4c18-916f-070a7cd40e9c.png)

I don't like "Indian mineral estate" or "Federal government's Indian energy," since neither is a proper noun (to my knowledge).
We can close this issue and circle back to this later, but I strongly feel that this bill was passed to have us alter our language and we should alter the language in these instances to get into compliance.

**Comment by mcharg** [comment]
@daniel-coleman-1 We should leave this issue open until @Maroyafaied can weigh in.

**Comment by CM805** [comment]
Don't forget to take this into consideration:  https://www.ecfr.gov/cgi-bin/text-idx?SID=8c05e819ce48df97fc7ad62ae9c63704&mc=true&node=se25.1.211_13&rgn=div8

I know it is hard when there is conflicting information.  I think it would be good for ONRR leadership to document how they come to whatever decision they make regarding this.

**Comment by mcharg** [comment]
@Maroyafaied Nichelle said they are going to start working on an ONRR style guide and want us to be involved.  That might be a good time to bring this up.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 We don't use Native American on onrr.gov so please take that section out in the wiki's content guide on onrr.gov.  Please take everything in red out for onrr.gov and leave just the "Indian" sentence.  We can revisit this when working with Nichelle on ONRR's style guide. 
![image](https://user-images.githubusercontent.com/40175688/127926275-e3897df1-d1b8-4fe4-9f5f-f613e00357cb.png)
