### ISSUE TITLE
Update Coal Excise Tax page with 2020 data 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1846]
https://revenuedata.doi.gov/how-revenue-works/coal-excise-tax

**Comment by Maroyafaied** [comment]
@Baymatt I added you on this issue since you've updated this before in issues #571 and #1266.

**Comment by lpgoldstein** [comment]
@Maroyafaied how should we handle the "d"? It stands for - [d] In order to avoid disclosure of information for specific taxpayers, these data have been deleted.  Data are included in appropriate totals. My thought it just to include a note at the bottom explaining that. We can't back into the number either because there are several cells that have a d listed instead of a number for 2020. 
![image](https://user-images.githubusercontent.com/39419003/143904551-97b5e463-10ed-4e5e-9ca0-1902a834448f.png)

**Comment by Maroyafaied** [comment]
@lpgoldstein I think we should only report the 131,231 for subsurface mining since that's all that was reported and we can't figure out what the d was from the total.
