### ISSUE TITLE
Explore data - oil & gas (pre-production) shows up as commodity in summary card

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1886]
Found this in explore data for Atlantic offshore

![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/7e093dd2-0519-4e74-b958-5a006d09faab)

**Comment by cthomasONRR** [comment]
@mojobnichols In explore data, when you select a specific commodity you will get other commodities aside from that selected commodity on the cards. Here are some examples. 

First, I selected wind only, and the Offshore Atlantic card displays wind AND oil and gas (pre-production):
![image](https://user-images.githubusercontent.com/72526208/146789008-7a976286-a912-4f52-91e2-13d365e5bcd7.png)

Second, I selected geothermal only, and the CA card displays geothermal AND oil and gas:
![image](https://user-images.githubusercontent.com/72526208/146789265-9bd718ea-be90-4e75-bce2-2f5d4bd0f7de.png)

Third, I selected geothermal only, with the New Mexico card does NOT display geothermal at all:
![image](https://user-images.githubusercontent.com/72526208/146789481-e0bfe13f-b01e-4793-8608-5a8cc7634844.png)

**Comment by cthomasONRR** [comment]
@Maroyafaied @mcharg @mojobnichols 

After looking at this issue more closely, I do not think that there is a bug/error here. The summary cards list the top 3 commodities for each location selected, regardless of which commodity you have decided to filter to.

Here's an example: I have geothermal, wind, and oil selected for the commodity filter. When I click on New Mexico, the summary card lists oil, NGLs, and gas under "Top Commodities", because those are the highest revenue values. At the bottom of the card, it says "Total Commodities: 9", which indicates that there are indeed more commodities than oil, NGLs, and gas, but those are the top 3.
![image](https://user-images.githubusercontent.com/72526208/148260479-319a1c20-3f35-4a87-b7e2-4de9086ac337.png)

The filtered commodities are featured below in the Compare Revenue section. They are just not featured on this summary card by design.

Here are 2 ideas Mojo and I discussed:
1. For the "Total Commodities: #" line at the bottom of each summary card, we could do a mouse-over that would expand and show all additional commodities.
2.  We could do some user testing on the summary cards to see if we should modify the "Top Commodities" section, either by rewording or with a different visual.

Maroya and Shannon, let us know if you think we have the 'appetite' to work on this modification right now. And please let me know if you have any questions. Thanks!

**Comment by mcharg** [comment]
@cthomasONRR We have an issue to add an indicator of what commodity you have selected that might address this.
https://app.zenhub.com/workspaces/open-data-design--development-5464fa79c3cc8d7f4c384eaf/issues/onrr/nrrd/1437

**Comment by Maroyafaied** [comment]
@cthomasONRR I must of been thinking that I was in the production filter and not revenue in explore data but you are right there's no bug here, by design the summary card for revenue shows all commodities by location.  Sorry for the confusion on my part, I'm good closing this issue and I don't think there's a need to look into this as of now. @mcharg @mojobnichols do you agree?

**Comment by cthomasONRR** [comment]
@mcharg I looked at the OGOR Production prototype, and I'm not sure how that would work in cases where multiple commodities are selected... we can set up a meeting to discuss if you'd like.

**Comment by Maroyafaied** [comment]
@cthomasONRR you can't select multiple commodities in the production filter for explore data.
