### ISSUE TITLE
Iterate on renewables design from design studio

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#1897]
@mcharg to do a bar chart with renewables vs non-renewables.

@jkwonatx to explore what we can do with disbursements data and production data.

@cthomasONRR will do research on whether we can convert production numbers to lightbulbs.

**Comment by mcharg** [comment]
This is what it looks like with a stacked bar chart with renewables vs. non-renewables.  You can barely see the renewables.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/65896d80-a5a9-4ece-b82c-564159fef7fa)

**Comment by mcharg** [comment]
The percentages are mostly less than 1%, so they also wouldn't show up on a pie chart.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/2fae05d1-83fa-4f61-9e43-1c04632a47e4)

**Comment by mcharg** [comment]
Here's an option that shows the tiny slice for renewables along with a breakout of geothermal and wind within that slice.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/651084fb-1dce-4eb8-9e11-889546f5ae00)

**Comment by mcharg** [comment]
Spreadsheet with the numbers I used, in case anyone else wants to play with it.
https://doimspp.sharepoint.com/:x:/r/sites/NRRD/Shared%20Documents/General/NRRD/Design/Renewables%20Fact%20Sheet/Sketches/RenewableRevenue.xlsx?d=w2ccb7ea61c10484f8fc2ac2a2b7187cc&csf=1&web=1&e=G7ndIv

**Comment by jkwonatx** [comment]
https://miro.com/welcomeonboard/aExlNUp4aEpMSENwaGJrQzJxaFN3UHhqVmFxTDZZbEVhOXAxY0RCempxeXlVSEcySGhHYUM0dlB3UlRqb3NyV3wzMDc0NDU3MzYxNDk2OTQ0ODI3?invite_link_id=821363958953

**Comment by jkwonatx** [comment]
update: 12/23 -- I think this exercise is going somewhere. I put this together based on what I remember, so the next step I want to take is to refer to the design studio presentation to fill in blanks and check for any misunderstanding on my part. 

![all](https://user-images.githubusercontent.com/85380376/147293227-b1e3ea40-f01e-4c3c-90ee-cbbbf7292d12.png)
![1](https://user-images.githubusercontent.com/85380376/147293233-58ba838c-efa6-4cbf-92b3-7fd53784d77f.png)
![2](https://user-images.githubusercontent.com/85380376/147293240-8c0053be-0dd6-4c0f-a044-f822a76f4bcd.png)
![3](https://user-images.githubusercontent.com/85380376/147293244-7ee2efb1-b747-40c0-a961-7c75b9edc16f.png)
![4](https://user-images.githubusercontent.com/85380376/147293251-f5fbc655-76c5-4582-aaf1-f2f592ea158a.png)
![5](https://user-images.githubusercontent.com/85380376/147293257-16eca1f5-402d-4068-84b5-32091ce65ac6.png)

**Comment by cthomasONRR** [comment]
I talked with Maroya about converting production numbers to lightbulbs. She would like to keep our first draft to have existing data only. If Kimbra wants something else, we can then add this concept to it.

I did some initial research, and found some very rough estimates for powering homes for a year. This seemed be be a better comparison than lightbulbs, because we are dealing with such large production numbers. 

I can take some of these general conversions and try to apply them to units other than Kilowatt hours, but for right now Maroya would like me to hold off and focus on other work.

![image](https://user-images.githubusercontent.com/72526208/147590066-0d1e7b70-764c-4f8c-b577-e9262f99ad0b.png)

**Comment by mcharg** [comment]
@jkwonatx Your mind map is a great way to visualize the problem.

**Comment by jkwonatx** [comment]
How we'd describe (qualitatively) a successful fact sheet: 

- Use data visualization we already have
- Summarizes our data on the renewables effectively
- Useful to the users
 *consider including a section for the content -- insightful, educational
 
 I'll keep them in mind as I work on the prototypes. I appreciate all the positive feedback on my little Miro board. Hope that was worth your while. 
 
 I'll have a couple of prototypes for next week's interns meeting.

**Comment by cthomasONRR** [comment]
I saved the renewables disbursement data excel sheet [here](https://teams.microsoft.com/l/file/5470509C-E945-460C-81E8-8416C8C7555C?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=xlsx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FDesign%2FRenewables%20Fact%20Sheet%2FDisbursements_Renewables.xlsx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a). Here are some image ideas. (All graphs are in the excel too.)

Geothermal 201-2021, and 2021 only:
![image](https://user-images.githubusercontent.com/72526208/148226864-dd3e2229-b74c-4e62-8bf3-622d2f5ec9e8.png)
My concern with the 2021 geothermal data is that there are negative values, which we will have to take space on the infographic to explain.

Wind 2017-2021, and 2021 only:
![image](https://user-images.githubusercontent.com/72526208/148227071-266b0792-67f9-4c04-9803-49413a45147f.png)
Wind disbursements are so dominated by U.S. Treasury that is doesn't make an interesting visual.

Combined Geothermal and Wind Disbursements, for 2021 only:
![image](https://user-images.githubusercontent.com/72526208/148227716-f98e6989-c13f-43de-95eb-fa2db966f1ac.png)
Showing recipient details in the bar chart leads to the same issues mentioned above. Maybe the way to go is this simple pie graph just showing the grand total for both geothermal and wind.

@mcharg @Maroyafaied @jkwonatx Let me know what yall think! Maroya, I know you requested no new visuals, so maybe this will be waiting for second draft if Kimbra asks for us to include disbursements?

**Comment by Maroyafaied** [comment]
@cthomasONRR thanks for working on this, the negative numbers for Geothermal would raise questions and need to be explained.  I still think we start with a prototype that doesn't involve new visuals and have the disbursement visuals in another prototype in case there's interest in it.

**Comment by cthomasONRR** [comment]
@Maroyafaied I agree. I think my last pie chart with just 2021 grand totals (no recipient breakdowns) is the way to go if we're asked to add disbursements.

**Comment by mcharg** [comment]
I agree, as well.

**Comment by mcharg** [comment]
We could also do a circle chart of the last option instead of a bar, if we want to use a chart style we already have.

**Comment by jkwonatx** [comment]
[Jae's Board - Renewable Fact Sheet.pdf](https://github.com/ONRR/nrrd/files/7848761/Jae.s.Board.-.Renewable.Fact.Sheet.pdf)

**Comment by jkwonatx** [comment]
[Jae's Board - Renewable Fact Sheet ver1.pdf](https://github.com/ONRR/nrrd/files/7848779/Jae.s.Board.-.Renewable.Fact.Sheet.ver1.pdf)

**Comment by jkwonatx** [comment]
@cthomasONRR the graphics you made above look great! I'll review them before today's interns meeting.

**Comment by jkwonatx** [comment]
Before the next interns meeting, I'll create a hi-fidelity sketch using Axure based on the feedback I received today at the interns meeting. Thank you all for your thoughts and feedback. 

[Jae's Board - Renewable Fact Sheet ver2.pdf](https://github.com/ONRR/nrrd/files/7850207/Jae.s.Board.-.Renewable.Fact.Sheet.ver2.pdf)

**Comment by jkwonatx** [comment]
Axure version. 

https://3tp68j.axshare.com

**Comment by mcharg** [comment]
@jkwonatx I added comments on the Axure prototype.

**Comment by jkwonatx** [comment]
Thank you! @mcharg I read the comments. I'll make changes this weekend.

**Comment by Maroyafaied** [comment]
@jkwonatx I need to look at this but I have a concern with showing disbursement if values are negative.

**Comment by Maroyafaied** [comment]
@jkwonatx this would be the FY21 disbursement data for Geothermal and Wind, I don't think we should display disbursement in this way because of the negative data. ![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/738f71d6-f213-4953-8ebc-725ef5cdda1e) 
Another idea is to display disbursement by state for just Geothermal or we don't do any disbursement data and just extend the revenue section and include revenue type tables you have on the right. @mcharg @cthomasONRR thoughts? 
 ![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/f19179cc-5a15-4bf4-b69b-c2e3712663b9)

**Comment by mcharg** [comment]
Or we could show that it's negative, so leadership can see it and realize why we don't want to show it.

**Comment by Maroyafaied** [comment]
@mcharg I'm not sure what the blank value is indicating but it looks like the negative disbursement funds are associated with it. 
![image](https://user-images.githubusercontent.com/40175688/149404355-40c89ada-11aa-4bb7-bfff-795578487021.png)

**Comment by mcharg** [comment]
@Maroyafaied I think it's all the disbursements to the federal government.

**Comment by cthomasONRR** [comment]
I think it's best to keep disbursement graphic as simple as possible. We will have a map for revenue and a ton data listed in tables for production. That's a ton of information. Maybe keeping disbursements simple will make the infographic more digestible? I feel like any why you try to subdivide disbursements, you run into issues with with negatives or blanks, and that leads to more questions than answer for the viewer.

Maybe this pie chart, converted to the circle graphics currently on the NRRD site (like Shannon initially suggested) is best:

![image](https://user-images.githubusercontent.com/72526208/149410336-5214c0ed-8e80-4d71-aeda-4eedccecdcdd.png)

**Comment by Maroyafaied** [comment]
@jkwonatx to summarize our discussion, we'll do 2 prototypes summarized below. Please don't hesitate to ask questions. Thanks

1st Prototype: Revenue - shows updated map with 9 locations with a table displaying top 4 and content in the bottom.  Disbursement - circle chart with table. Production-same

2nd Prototype: Revenue - shows updated map with 9 locations with a table listing all 9 locations without content.  Disbursements - no disbursements. Production-same

**Comment by cthomasONRR** [comment]
I'll have time first thing tomorrow morning to pull updated datasets. I will link to them here once I have them compiled. Thanks!

**Comment by cthomasONRR** [comment]
@Maroyafaied @mcharg @jkwonatx 

I pulled the most updated data from NRRD. I compiled the revenue, disbursement, and production data in a spreadsheet [here](https://teams.microsoft.com/l/file/E02E9A3E-9838-463C-A17F-51605DFF1213?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=xlsx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FDesign%2FRenewables%20Fact%20Sheet%2FRenewables_1-19-2022.xlsx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a)

Here is an updated screengrab of Revenue FY 21 for Renewables:
![image](https://user-images.githubusercontent.com/72526208/150145337-632563f9-928d-4dae-a834-3a1f032e8fa6.png)

For revenue data, there is a bit of revenue in 'location not published' that won't appear on the map:
![image](https://user-images.githubusercontent.com/72526208/150145862-e28446f9-d6dd-46b5-90ab-bd9c18afa2c9.png)

For disbursements, I had just CY 2021 previously. I had to manually get Fiscal Year 2021 because our FY datasets don't include commodity. I did this by getting CY 2020 and CY 2021 data by commodity in Query Data, and manually making the dataset include months in FY 21 only. Here are the true FY 21 Disbursement by commodity: 
![image](https://user-images.githubusercontent.com/72526208/150146644-f18630af-f12c-4ca8-b390-81bb56ff81e1.png)

For production, we only have FY 2020 right now. Here are those updated numbers:
![image](https://user-images.githubusercontent.com/72526208/150146825-3f6d333c-0431-4507-bdf0-d3f6605534c1.png)
On Query Data with the trendline:
![image](https://user-images.githubusercontent.com/72526208/150146987-9ec092e4-639c-4aa8-8b62-f3b24e104024.png)

**Comment by cthomasONRR** [comment]
Also, I did a "circle packing" image for disbursements using https://app.rawgraphs.io/

![image](https://user-images.githubusercontent.com/72526208/150150552-9da5dbb4-d71c-4843-9e19-866b77f9a7f3.png)

**Comment by jkwonatx** [comment]
Options A and B @mcharg @cthomasONRR @Maroyafaied 

https://bxuqc4.axshare.com

**Comment by mcharg** [comment]
@jkwonatx These look good.  Can you put them on separate pages in the prototype without the comments, so we have them clean to review with leadership?

**Comment by Maroyafaied** [comment]
@jkwonatx looks good, I put a couple of comments. Thanks

**Comment by cthomasONRR** [comment]
@jkwonatx @Maroyafaied @mcharg I added in some comments to the wireframe. It looks great! I just had some minor nit-picky things about the data. Let me know if anyone has any questions. Thanks!

**Comment by jkwonatx** [comment]
@cthomasONRR @Maroyafaied @mcharg I've made the update to the Renewables. 

https://n1ugvx.axshare.com

**Comment by jkwonatx** [comment]
https://mtm1pz.axshare.com

**Comment by cthomasONRR** [comment]
Updated Disbursements FY 21 data. I found a better way to pull this data. This is WAY more accurate than what I did previously. Apologies- I'm still new to Query data and should not have used it for this. We can add a blurb about disbursements going to the U.S. Treasury and State & Local Governments.

@jkwonatx Don't worry about updating this for the prototype tomorrow. We will emphasize that the data isn't finalized.

![image](https://user-images.githubusercontent.com/72526208/151035033-815f3689-529d-4002-95c5-73570a27cb3e.png)

**Comment by jkwonatx** [comment]
https://zw7izs.axshare.com

@mcharg @Maroyafaied I've made the update to Option A as we've discussed yesterday 
@cthomasONRR if you have a moment, could you check the disbursements copy ("Total disbursements from all commodities for FY 2021 were $8,776,260,163.  Geothermal and wind make up 0.24% of the total.") for accuracy? Thank you! 

![Screen Shot 2022-01-26 at 10 52 58 AM](https://user-images.githubusercontent.com/85380376/151209432-a23a9b46-2eae-4c51-8679-00f73117bea5.png)

**Comment by cthomasONRR** [comment]
@jkwonatx With my updated numbers, Geothermal and wind make up 0.26% of the total. Your total in the blurb are correct. The image I have in the comment above are the better disbursement values to use for geothermal and wind. The changes are minor, so don't worry about updating the numbers for today. We can reiterate to them that the numbers aren't finalized. Thanks so much for all your work on this!!!

**Comment by Maroyafaied** [comment]
@jkwonatx It looks great, I also ran the numbers and got the same as @cthomasONRR but I agree don't worry about making updates. 
![image](https://user-images.githubusercontent.com/40175688/151210924-4113743f-9cb6-456c-88b4-d8f70653156d.png)

**Comment by Maroyafaied** [comment]
The leadership team went with [Option A](https://zw7izs.axshare.com/#id=cfp7si&p=option_a) and asked to include trend line for disbursements and add content comparing year over year. I will close this issue and create another to proceed working on this.
