### ISSUE TITLE
Explore Data: Change National card to be Nationwide Federal

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#193]
And don't include Native American data.

**Comment by jennmalcolm** [comment]
@mentastc please review the numbers are right in dev.

**Comment by mentastc** [comment]
The below national card is missing revenues ie not all revenues are showing up in other. for instance NGLS don't appear and they account for 339 million while the other category is only 150 million. There are also other commodities that aren't accounted for but since its rolled into other I don't know what makes up other. 
![image](https://user-images.githubusercontent.com/15347998/76634883-eee9a280-651c-11ea-84f9-3a2ac32bcd5b.png)


![image](https://user-images.githubusercontent.com/15347998/76634823-d7121e80-651c-11ea-84c7-386811a4a56b.png)

**Comment by mentastc** [comment]
The revenue type chart is missing revenues.
![image](https://user-images.githubusercontent.com/15347998/76635189-733c2580-651d-11ea-87ad-11d2ac822829.png)
![image](https://user-images.githubusercontent.com/15347998/76635228-8222d800-651d-11ea-813f-e89332dcff67.png)

**Comment by mentastc** [comment]
I would also suggest having a total line that totals up all the revenues, this would confirm for the user that they are looking at the totality of all the federal revenues when working between the data sets/visuals.
