### ISSUE TITLE
Write data upload instructions for OGOR B

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#2010]

**Comment by cthomasONRR** [comment]
Do we want to add a section in the wiki here (https://github.com/ONRR/nrrd/wiki/Releasing-changes-to-production#how-to-upload-monthly-datasets) for how to upload new OGOR-B? Since OGOR-B will be replacing the current monthly production, I can revise the existing monthly instructions to remove anything about production and add a new section below specifically for OGOR-B production.

**Comment by Maroyafaied** [comment]
@cthomasONRR Yes we can add a section there specific to OGOR B but the instructions will be a bit different. If you want to start by adding a section, I can then edit the instructions.

**Comment by cthomasONRR** [comment]
@Maroyafaied Sounds good. I created a new section for us: https://github.com/ONRR/nrrd/wiki/Releasing-changes-to-production#How-to-upload-OGOR-B-Data

**Comment by Maroyafaied** [comment]
@cthomasONRR I drafted instructions, please review. Thanks

 https://github.com/ONRR/nrrd/wiki/Releasing-changes-to-production#How-to-upload-OGOR-B-Data

**Comment by cthomasONRR** [comment]
@Maroyafaied I reviewed and the instructions look good! I will use them next monthly upload and make any clarifying edits if needed. I'll close this issue now.
