### ISSUE TITLE
Fix pricing bug on pricing tabs

### ISSUE THREAD

**Issue by lpgoldstein** [ONRR/nrrd#2310]
Pricing tabs not loading correctly. If you try to select a year and pricing option via the filter you may get a "no data" label in each filter box and its impossible to refresh the page. This happens in both Edge and Chrome and it has been reported by ONRR employees. ![image.png](https://images.zenhubusercontent.com/5c59d3cd7592186396262002/3a0e8f28-7feb-4b05-837a-074e94d11c57)

**Comment by lpgoldstein** [comment]
https://onrr.gov/references/valuation?tabs=pricing,indian-gas-index-zone&years=2021&designated_area=Oklahoma

The bug isn't happening for all users.

**Comment by lpgoldstein** [comment]
More information from 2 employees - !st working from home and 2nd person in office

1. my IBMP worked, hers did not
2. her gas index worked, mine did not
3. neither of us got gas major portion to work

**Comment by cthomasONRR** [comment]
I got this "No data available" bug by:

1-  Just by navigating to the page and trying to select a filter.
2- After getting the bug in "1", I refreshed the page and was then able to select area and year filters.
3- After refreshing the page with area and year filters selected, I got the "no data available" bug again.

**Comment by Maroyafaied** [comment]
![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/aba91442-0b4b-42f2-9585-f1676045b714)

**Comment by mojobnichols** [comment]
It doesn't appear to  related to the null $ID error.   I saw it occur without that.   And I have seen i work when this error is show even show twice.

**Comment by greensomes** [comment]
The collection Vue components were arbitrarily waiting 300ms before building the select component lists from the collection data. In some cases, the API calls to get the collection data was taking longer than 300ms, so there was no data available when the lists were built. Thus, the "no data available" values. The fix was to watch the loading property of the collection API call to flip to "0" before building the lists.
