### ISSUE TITLE
Get approval to speak at FSI tech talk

### ISSUE THREAD

**Issue by lpgoldstein** [ONRR/nrrd#2337]

**Comment by Maroyafaied** [comment]
@lpgoldstein I'm moving this to next week since Nathan is out this week. I'm also adding your write up to this issue. Thanks

We have been invited to speak at the Foreign Service Institute Tech Talk (FTT). The Foreign Service Institute is a a a part of the U.S. Department of State. This is a monthly 60 minute interactive speaking series where government tech innovators speak on a specific subject as subject matter experts. The speaking series is virtual and free to attend for State Department employees. 

We have been asked to present about how we work as an Agile team in government and share our websites. This topic is similar to other presentations we've given and the information is already available through our public blog and wiki.

**Comment by Maroyafaied** [comment]
@lpgoldstein adding this back to this sprint, I was asked to get approval from the Ethics Counselor. I sent an email requesting approval.

**Comment by Maroyafaied** [comment]
@lpgoldstein we have permission from Howard and ethics counselor
