### ISSUE TITLE
Read Fifth U.S. Open Government National Action Plan

### ISSUE THREAD

**Issue by lpgoldstein** [ONRR/nrrd#2353]
Read the new plan https://open.usa.gov/national-action-plan/5/

**Comment by cthomasONRR** [comment]
Here are sections I found relevant to the ODDD team, and some comments about how we are working on these goals.

Access to data: https://open.usa.gov/national-action-plan/5/#improve-access-to-government-data-research-and-information. Clearly, this one is important to us because of NRRD and reporting/paying info on ONRR.

Because of the following subsection: 
- “Expand the Federal Government’s Production, Dissemination, and Use of Equitable Data.” https://open.usa.gov/national-action-plan/5/#expand-the-federal-governments-production-dissemination-and-use-of-equitable-data. There are 5 key recommendations: 
   - (1) making collection and analysis of disaggregated data the norm while protecting privacy. ODDD and DORC are continuously doing this by posting granular data on a monthly basis while protecting PII.
   - (2) building on existing Federal infrastructure to leverage underused data, including through interagency data sharing. ODDD is working on this by continuously making sure the NRRD site is audited and user-friendly. The redesign of onrr.gov also would fit here because we made access to that information easier and more user-friendly.  
   - (3) building capacity for robust equity assessment for policymaking and program implementation, including by investing in statistical, evaluation, and data science expertise. ODDD’s hiring and work to be a fully-staffed team fit here. 
   - (4) galvanizing diverse partnerships across levels of government and the research community, especially through opportunities for mutually beneficial uses of data. ODDD’s outreach work, in-agency cross training, and use of Open Opportunities fits here. 
   - (5) being accountable to the American public by providing tools that allow for civil society organizations and communities to use and visualize government data and chart progress towards more equitable outcomes. Reiterating the continuous audits/improvements on NRRD and the onrr.gov redesign fit here.

Gove service delivery is also relevant to us: https://open.usa.gov/national-action-plan/5/#transform-government-service-delivery. This section talks about an “open” government, which we are clearly achieving by having all our work in the open.

Because of the following subsections:
- “Improve High Impact Service Providers and Ensure Ongoing Accountability.” https://open.usa.gov/national-action-plan/5/#implement-the-executive-order-on-transforming-federal-customer-experience-and-service-delivery-to-rebuild-trust-in-government. Most of this subsection is mainly about delivery of gov services at critical times in peoples lives. Even though we aren’t considered a “high impact service”, we incorporate transparency and accountability in all our work functions. They mention feedback data and surveys, which I think our UX research would fit into this category.
- “Prioritize Administrative Burden Reductions through the Paperwork Reduction Act.” https://open.usa.gov/national-action-plan/5/#prioritize-administrative-burden-reductions-through-the-paperwork-reduction-act. We actively make sure none of your UX research is a PRA burden for anyone. We also work closely with our Regulations team to make sure their PRA information is posted clearly and in a timely manner.

Government Integrity: https://open.usa.gov/national-action-plan/5/#counter-corruption-and-ensure-government-integrity-and-accountability-to-the-public. Most of this is about criminal justice, but there is a relevant FOIA subsection…

-	https://open.usa.gov/national-action-plan/5/#strengthening-access-to-government-information-through-the-freedom-of-information-act-foia. I think we are already meeting this subsection by regularly improving and expanding our publicly-posted data, with collaboration from DORC to capture FOIA requests and make those requests public.

**Comment by lpgoldstein** [comment]
Added the pdf to a folder within "Goals and Accomplishments" called Supportive documentation. We can store anything relevant that supports our existence - https://doimspp.sharepoint.com/:f:/r/sites/NRRD/Shared%20Documents/General/Admin/Goals%20%26%20Accomplishments/Supportive%20documentation?csf=1&web=1&e=7zeb0c

**Comment by lpgoldstein** [comment]
Maybe a short blog post?

**Comment by lpgoldstein** [comment]
In the first section - “Expand the Federal Government’s Production, Dissemination, and Use of Equitable Data." ...Furthermore, the Government has an important role to play in ensuring that public websites, meetings, and documents are accessible and compliant with Sections 504 and 508 of the Rehabilitation Act (Public Law 93-112) to enable the full participation of individuals with sensory and mobility disabilities in Federal Government—and civil society...We have worked extensively in this area and are continuing to improve.

**Comment by eelzi-ONRR** [comment]
My notes on specific sections. Some parts of the plan are important and were good to read, but not really applicable to ONRR or ODDD. Overall I think we're doing great and nothing in the plan would affect us in a huge way - but it could be good to use as a means to guide future goals and improvements.

**Advancing Equity and Inclusion for Underserved Communities:** Has me thinking about how, even though our target audiences are pretty specific compared to a lot of other government sites, can we still make our sites easy to use and content more understandable for the general public as well. Even when the jargon and concepts are complicated - what can we do to make them less so? Just putting info out there isn't necesssarily transparancy for all if it's difficult to understand. We also might get increased use by the question answerers and storytellers user groups if our information and data were even easier to use.

**Improve Access to Government Data, Research, and Information**
 **Expand the Federal Government’s Production, Dissemination, and Use of Equitable Data** We might website adjustments based on the results of Requests for Information from the public to inform efforts on how Federal agencies can create partnerships and collaborations to share data with local communities, Tribal, territorial, State, and local governments, and researchers.
 
These two could maybe affect natural resources use in general and indirectly then affect us: **Set Government-Wide Federal Sustainability Goals** and **Establish Agency Plans, Targets, and Reporting & Building Public Tools and Data to Advance Environmental Justice.**

**Improve Public Engagement Related to Agency Regulatory Actions** - ONRR in general might be affected by this since it's led by OMB, but I don't know that it specifically affects ODDD. But if ONRR were to hold public sessions ro gather public input on rulemaking - we might need to make that information easily available on the website. Possibly on the homepage.

**Improve High Impact Service Providers and Ensure Ongoing Accountability** We're not a high-impact service provider, but if ONRR is eventually required to make a CX page, we would have to add that to the site.

**Implement Open Government Components of a New Government-Wide Strategy on Countering Corruption** - seems like this one is a good justification for our work.

**Bolster the Trust and Independence of Federal Statistical Agencies and Federal Statistics** - This one defintely affects us. We're really good at it the 4 aspects of the Statistical Policy Directive 1:  1) relevance and timeliness, 2) accuracy and credibility, 3) objectivity, and 4) confidentiality and exclusive statistical use of data.  So we just need to keep up the work and make sure our site functions as expected and displays the updated data for everyone.

**Comment by lpgoldstein** [comment]
This is probably what Amanda is using to justify their work at the PPS: **Develop Open Innovation Techniques to Engage the Public in Federal Procurement Policymaking. The Federal**
Government must ensure that it spends money wisely and eliminates waste and abuse of taxpayer dollars. With
approximately one out of every three dollars of Federal Government discretionary spending going to contractors, it is imperative that contract actions result in the best value for taxpayers. This creates an opportunity to
leverage procurement, consistent with applicable law and regulations, to take on our most pressing challenges
as a country, such as advancing equity and securing domestic supply chains. In order to identify and develop the
best ideas for how procurement can be used to address our most pressing complex and crosscutting challenges,
the Office of Federal Procurement Policy in the Office of Management and Budget is using open innovation
crowdsourcing with the support of an online platform to collaborate with the public on ways to improve government procurement. As a result of crowdsourcing campaigns undertaken over the last 18 months, the Federal
Government was able to (1) expand our reach to allow a greater number and diversity of voices to participate
in the procurement process, (2) gain new insights and perspectives, (3) explore problems and solutions, and
(4) accelerate the process of identifying the most promising ideas for reforming Federal procurement. During
Fiscal Year 2023 the Federal Government commits to continuing to use open innovation techniques and crowdsourcing tools to foster meaningful dialogue with individuals and organizations with expertise and interest in
Federal procurement matters.

**Comment by Maroyafaied** [comment]
@lpgoldstein @eelzi-ONRR @cthomasONRR Thank you all for taking detailed notes! I read the plan and your notes. Closing this issue.
