### ISSUE TITLE
Build sitemap for homepage 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#2367]

**Comment by eelzi-ONRR** [comment]
Home page, footer, explore and query sections are done. Will finish downloads and how it works next sprint.

http://127.0.0.1:32767/start.html#id=gy27ii&p=0_0_homepage&sc=3&g=1


I'm going to wait until the whole thing is complete to have reviewers since as I keep working on it, I find things to improve that affect pages I thought I was done with
