### ISSUE TITLE
Update "Joining our team" section of NRRD wiki

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/nrrd#2373]
https://github.com/ONRR/nrrd/wiki/Joining-the-Open-Data,-Design,-and-Development-(ODDD)-project-team

Include more info about our team and add onrr.gov as one of our products.

**Comment by cthomasONRR** [comment]
And also here: https://github.com/ONRR/nrrd/wiki

**Comment by cthomasONRR** [comment]
And also here: https://github.com/ONRR/onrr.gov-site/wiki

**Comment by cthomasONRR** [comment]
@Maroyafaied want to review?

At https://github.com/ONRR/nrrd/wiki/Joining-the-Open-Data,-Design,-and-Development-(ODDD)-project-team, I updated:
- Products we maintain to include onrr.gov and the blog
- Project team to include the table of roles and responsibilities
- Meetings to include a brief Agile intro, and sections about our 2-week sprints and long-term planning

At https://github.com/ONRR/nrrd/wiki, I updated:
- Products we maintain to include onrr.gov and the blog
- Team to include a link to the "joining our team" section
- Project background to include entire timeline

At https://github.com/ONRR/onrr.gov-site/wiki, I updated:
- Project background to include a link to the NRRD wiki for full history
- Team section to include a link to the NRRD "joining out team" section

**Comment by cthomasONRR** [comment]
@AlexandracmONRR When you have time can you review?

**Comment by AlexandracmONRR** [comment]
@cthomasONRR yes, I'll do this review today.

**Comment by AlexandracmONRR** [comment]
I will submit my feedback/edits in 3 comments - 1 comment for each link:

(1/3)
At https://github.com/ONRR/nrrd/wiki/Joining-the-Open-Data,-Design,-and-Development-(ODDD)-project-team:
Under Meetings section:
- teamwork, self-organization and accountability [_should add comma between organization and accountability_]
- The product manager will invite you to each. [_should this be "product owner" so that it aligns with Maroya's role?_]
- Each 2-week sprint includes daily standups, sprint planning, weekly synch up, sprint demo, and sprint review/retro. [_we may want to clarify cadence for all meetings, since some are defined, try this "Each 2-week sprint includes bi-weekly sprint planning, bi-weekly sprint review/retro, daily standups, weekly synch up, and weekly sprint demo."_]
- We conduct ad hoc design studios, as needed, to shape solutions for larger projects. 
[_ad hoc design studios aren't defined, what happens in these design studios? Potentially, this could include user interviews, user research planning, problem/solution brainstorming, user testing, prototyping._]

**Comment by cthomasONRR** [comment]
@AlexandracmONRR I've made the following updates: 

- teamwork, self-organization, and accountability
- Each 2-week sprint includes: daily standups, weekly synch up, bi-weekly sprint planning, bi-weekly sprint review/retro, and bi-weekly sprint demo.
- We conduct ad hoc design studios, as needed, to shape solutions for larger projects. Ad hoc design studios occur when there is a request for a new product or we see an area to improve upon. Design studios usually include group brainstorming, individual prototyping, sharing and hole-poking of prototypes, and coming to a decision on a prototype. User testing and user research can also be involved.

**Comment by AlexandracmONRR** [comment]
(2/3)
At https://github.com/ONRR/nrrd/wiki:
No edits for this!

(3/3)
At https://github.com/ONRR/onrr.gov-site/wiki:
No edits for this!

**Comment by cthomasONRR** [comment]
@AlexandracmONRR Thanks for reviewing!
