### ISSUE TITLE
Q/A testing of cloud.gov

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#243]
Look at about page
How it works
downloads

**Comment by alenahuang** [comment]
### All Pages
- adjust header styles (need to be different from the text below; also seen in table headings)
 ![image](https://user-images.githubusercontent.com/36544297/77199770-60929500-6ab7-11ea-870f-b661d7651975.png)

- space before "source code"
![image](https://user-images.githubusercontent.com/36544297/77198340-cd586000-6ab4-11ea-9073-a2f3d6a0b2af.png)

---------

### About Page

- white spacing of light blue and dark blue boxes seem off
- within the light blue box, "Laws and regulations" and "Oil, gas, minerals, and renewable energy" do not take you the specific section
![image](https://user-images.githubusercontent.com/36544297/77197795-c67d1d80-6ab3-11ea-8592-2d434eaa9048.png)

- add a ')' at the end of the abbreviation
![image](https://user-images.githubusercontent.com/36544297/77199699-448ef380-6ab7-11ea-92c3-02ac82dfbe90.png)


- In the history section, the definition popup for "EITI Standard" is too long, can't read because it goes off the page (and can't scroll down to see it all)
![image](https://user-images.githubusercontent.com/36544297/77198191-7e122f80-6ab4-11ea-9605-ba2915d3948f.png)

---------

### How It Works Main Page
- white spacing of light blue and dark blue boxes seem off as well
![image](https://user-images.githubusercontent.com/36544297/77198538-2627f880-6ab5-11ea-856f-70c551f1219f.png)

- it might be nice to have more spacing in between sections
![image](https://user-images.githubusercontent.com/36544297/77198711-81f28180-6ab5-11ea-80e2-3b9faecee021.png)

- more space between last body/content line and footer (seen on all How it Works pages)
![image](https://user-images.githubusercontent.com/36544297/77198735-90409d80-6ab5-11ea-93a3-22b2a07c2850.png)

- links say "Learn more about economic impact" rather "Coal" "Renewable"...
 ![image](https://user-images.githubusercontent.com/36544297/77199242-85d2d380-6ab6-11ea-8e54-9a64c8d5ef7c.png)

- link should be consistent with "Learn more about... "
![image](https://user-images.githubusercontent.com/36544297/77201504-9422ee80-6aba-11ea-91c4-508474a6f29e.png)

---------

### Individual "How It Works" pages
- How It Works / Federal Laws: remove '>' before "not specified" 
![image](https://user-images.githubusercontent.com/36544297/77200147-00e8b980-6ab8-11ea-97f9-1e32eb51e5de.png)

- How It Works / Native American Revenue: add more spacing below the table
 ![image](https://user-images.githubusercontent.com/36544297/77200506-b0259080-6ab8-11ea-904a-fed091895cec.png)

- How It Works / Onshore Oil and Gas: left side dropdown has bolded text? not sure if this is supposed to be
 ![image](https://user-images.githubusercontent.com/36544297/77200646-009cee00-6ab9-11ea-91ce-f1c9ab09fdb2.png)

- How It Works / Coal: no header to indicate it's the "Coal" page

- How It Works / Nonenergy Minerals: the white spacing is not consistent to the other "How It Works" pages
![image](https://user-images.githubusercontent.com/36544297/77200798-4ce82e00-6ab9-11ea-82b1-f6b347392a66.png)

- How It Works / Onshore Renewables: should have white space on the bottom of the top section like the other pages to break up the sections
![image](https://user-images.githubusercontent.com/36544297/77200960-a4869980-6ab9-11ea-837c-abc4012ce1e7.png)

- How It Works / Offshore Renewables: no background graphic like other pages (?)

- How It Works / Revenues: the tables don't line up for each section (see bonuses), some green lines do not extend all the way; overall, the table is very confusing to look at because the sections of text seem to be floating
![image](https://user-images.githubusercontent.com/36544297/77201126-f29b9d00-6ab9-11ea-997f-67c2dc799b44.png)

- How It Works / Audits: two download icons (second one is not consistent)
![image](https://user-images.githubusercontent.com/36544297/77201676-e532e280-6aba-11ea-8ab4-90e850ef1294.png)

---------

### Downloads Individual Pages

- All Pages: the definitions are hard to read... have something to separate word and definition?
![image](https://user-images.githubusercontent.com/36544297/77201806-24613380-6abb-11ea-92fa-7978121a0351.png)

- Downloads / Production By Month: error, need to relink
![image](https://user-images.githubusercontent.com/36544297/77201940-6a1dfc00-6abb-11ea-9319-35f3602fcf9f.png)



￼
