### ISSUE TITLE
table confusion

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#272]
We need to review the headings and content in the tables here https://dev-nrrd.app.cloud.gov/how-it-works/revenues.

Decide what to keep/change/remove.

**Comment by mcharg** [comment]
FYI - This was the old issue where we changed from an image to this table.
https://github.com/ONRR/doi-extractives-data/issues/3067

**Comment by Maroyafaied** [comment]
@jennmalcolm @lpgoldstein I was digging through old issues and this is the titles we used for headings for the phases. I think we should just go back to that and it wouldn't be confusing,

This is the original headings 
![image](https://user-images.githubusercontent.com/40175688/80640834-37074a80-8a21-11ea-81e7-95c0ade81349.png)

This is what we have now 
![image](https://user-images.githubusercontent.com/40175688/80640891-4be3de00-8a21-11ea-9e40-b491dfff2379.png)

**Comment by lpgoldstein** [comment]
@Maroyafaied I agree.

**Comment by Maroyafaied** [comment]
@jennmalcolm, it seems that before we included rents & fees together  under the pre production phase instead of separating them out as we do now.  

![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/733fb70a-dd19-405d-96cd-b635f1185504)

![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/f8b8feb8-e574-4c61-aefc-564cdfeee240)

**Comment by jennmalcolm** [comment]
Yes, thanks, @Maroyafaied. I think that it makes sense to put the fees that are pre-production into that column. Others are during production, so we'll just have to make sure to put them into the right place, as the previous tables had them.
