### ISSUE TITLE
Add Native American card for disbursements & revenue

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#340]
Clicking the option to do that does nothing right now.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/7ec84914-3c91-4b5d-a61a-2b7304b88ae0)

**Comment by mcharg** [comment]
This also isn't working for revenue right now.

**Comment by jennmalcolm** [comment]
From my testing, the plus on the detailed cards works to add Native American, but the one by the summary cards does not. The Native American disbursments summary card does say no disbursments, so we will need to change that wording, since that's not accurate. 

![image](https://user-images.githubusercontent.com/30806839/81188551-71be3500-8f83-11ea-962e-296683d3db35.png)

**Comment by mcharg** [comment]
This appears to be fixed in dev.
