### ISSUE TITLE
Update reference to Native American revenue

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#496]
The copy mentions tables below, which are no longer there and the documentation link needs capitalization.  We should consider linking to the query tool.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/ebfa111b-826d-4a68-ae28-fbec1b3ee14e)

**Comment by Maroyafaied** [comment]
@mcharg , I think it's supposed to say in the table above instead of below, there is a table of revenue collection on top of the page.  Let me know if you're ok to changing the wording to "above" and I'll change the capitalization and link to query tool. 
![image](https://user-images.githubusercontent.com/40175688/84675794-f9d01c80-aee9-11ea-93ce-828ed3b8dd79.png)

**Comment by mcharg** [comment]
I think it was actually referring to the tables we had before we replaced them with the links to the query tool.  Maybe we should just drop the whole Revenue Data section until we can add links to the query tool.

Current site:
![image](https://user-images.githubusercontent.com/38465926/84678373-ef1f8280-aefd-11ea-94e9-c7e790998606.png)
