### ISSUE TITLE
Explore Data: Ensure appropriate analytics are hooked up

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#55]
Define what we want to track and set it up to track it.

**Comment by mcharg** [comment]
Events to add:

Explore data:
- [ ] Data type selection
- [ ] Filter selection
- [ ] Add card
- [ ] Remove card
- [ ] Year slider interaction

Homepage:
- [ ] Homepage tab clicks
- [ ] Homepage link clicks
- [ ] Yearly/monthly toggle clicks

Query tool:
- [ ] Data type selection
- [ ] Filter selection

**Comment by mcharg** [comment]
I think the list above is a good start and we are ready to start putting in tags in an upcoming sprint.

**Comment by jlouis-onrr** [comment]
@mcharg, I've added a gtm preview environment for this branch .  If you would like to view the current tags installed, check out this link:

[https://www.googletagmanager.com/start_preview/gtm?uiv2&id=GTM-NCRF98R&check_preview_status=1&gtm_auth=KvrX6xRFvPqCLzDPz8QKpw&gtm_preview=env-93&gtm_debug=x&url=https%3A%2F%2F55-ensureappropriateanalyticsarehookedup.app.cloud.gov](gtm_preview)

I'll also be adding a preview for dev, so that we can verify the tags there as well

**Comment by mcharg** [comment]
@jlouis-onrr Site search also appears to not be tracking in the analytics.

**Comment by mcharg** [comment]
@jlouis-onrr Pages with and without / are showing up separate in the analytics.  Not sure if you can do anything about that.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/d4db2908-8ae0-4ed7-9505-8db712298679)

**Comment by jlouis-onrr** [comment]
@mcharg, I'll want to look at stripping the trailing slash if it exists.  I think I briefly started looking at this, but I think there was conflicting issue with stripping the trailing slash plugin and the query params plugin.  I'm going to look into it a bit further to see how I might solve this.

**Comment by mcharg** [comment]
Found everything in Google Analytics.
