### ISSUE TITLE
Consider adding context around why we collect royalties on some minerals that usually fall under the general mining act or the materials act

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#602]
Explanation from Solids group 

While not generally covered by the Minerals Leasing Act of 1920, ONRR does collect royalties on certain locatable minerals usually covered by the General Mining Act of 1872 (gold, silver, copper, etc) and salable or mineral materials usually covered by the Materials Act (limestone, clay, sand and gravel). These locatable and salable mineral leases are usually acquired by the Federal government in land swaps.  An example is where the Forest Service wants to exchange land it owns for private land that benefits both the private party and the Federal government, but there are other occurrences where this happens.  The key is that in these situations, the mineral rights have previously been exercised by the private party prior to the land swap so that the government inherits the contract obligation that the private party had connected to the land it transfers to the government.  In these cases, the government will honor any existing lease terms (including collection of royalties) that accompanies the land it gains in the exchange.  

Royalties are collected on the production from these acquired leases, but generally there is no rent associated with these type of leases unless specified in the specific lease terms. Since royalties are being collected, these leases are at least partially governed by the 1920 Mineral Leasing Act. But upon acquiring these leases, the lease terms may not change so the language may be very different from what can be found in a standard Federal lease.

**Comment by lpgoldstein** [comment]
@jennmalcolm I've revised the above text and combined it with what we currently have in How revenue works. It still seems like a confusing explanation. We can discuss in our weekly meeting. 

The General Mining Act of 1872 regulates gold, silver, cinnabar, copper, and “other valuable deposits.” Despite some amendments, this legislation still governs extraction of many nonenergy minerals, in particular hardrock locatable minerals on federal public domain lands.
These locatable and salable mineral leases are usually acquired by the Federal government in land swaps. An example is where the Forest Service wants to exchange land it owns for private land that benefits both the private party and the Federal government, but there are other occurrences where this happens. The key is that in these situations, the mineral rights have previously been exercised by the private party prior to the land swap so that the government inherits the contract obligation that the private party had connected to the land it transfers to the government. In these cases, the government will honor any existing lease terms (including collection of royalties) that accompanies the land it gains in the exchange.
Royalties are collected on the production from these acquired leases, but generally there is no rent associated with these types of leases unless specified in the specific lease terms. Since royalties are being collected, these leases are at least partially governed by the 1920 Mineral Leasing Act. But upon acquiring these leases, the lease terms may not change so the language may be very different from what can be found in a standard Federal lease.
The Minerals Leasing Act of 1920 limited the scope of the 1872 Act, providing different regulations for energy-producing minerals such as coal, oil, and natural gas. The Acquired Lands Mineral Leasing Act of 1947 and the Federal Land Policy and Management Act of 1976 govern mining on acquired lands.

**Comment by lpgoldstein** [comment]
Closing to work on correcting page in issue #758
