### ISSUE TITLE
Test to see if the download file matches the field order in the filtered view

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#655]
One participant complained about this in a user interview.

**Comment by jennmalcolm** [comment]
Might be fixed in dev already, so do some testing to verify if this is still an issue.

**Comment by jennmalcolm** [comment]
Currently in dev, the sorting is not the same in the download as it is on the screen. It seems to be sorting by the second column, rather than keeping the lines in the same order as the site. ![image.png](https://images.zenhubusercontent.com/5c59c5bee180620812ea29eb/b92ece37-2a1a-47ff-9a02-960db56e6828)
