### ISSUE TITLE
Offshore region cards have top locations for production

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#667]
Gulf of Mexico card:
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/4cb24986-2098-48e4-a88c-38cddf5f75d0)

**Comment by jennmalcolm** [comment]
Top locations should only be on nationwide and states

**Comment by jennmalcolm** [comment]
Also, state cards should show counties in top locations--not the same as the nationwide.

**Comment by mcharg** [comment]
Production card when there's no data for a state is pulling in the top locations nationwide.
![image](https://user-images.githubusercontent.com/38465926/87805048-bdfae080-c822-11ea-86ba-bf880f5fdaad.png)

**Comment by Maroyafaied** [comment]
![image](https://user-images.githubusercontent.com/40175688/87975161-7d040580-ca88-11ea-8ab5-b31fabd33426.png)

**Comment by jennmalcolm** [comment]
@jlouis-onrr it looks like the offshore card top locations are gone, but they are still appearing on the Native American card, and they are not appearing (by county) on the state cards. Since this is correct in beta, I think we should try to fix that before the release. 

![image.png](https://images.zenhubusercontent.com/5c59c5bee180620812ea29eb/61818aea-2167-4172-abcd-30bef1c75ac7)

**Comment by mcharg** [comment]
@jlouis-onrr Where is this ready to review?  I'm not seeing it in your #706 PR.
