### ISSUE TITLE
Refine wording for when there is no data

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#715]
Saying "since 2003" may make people think that it means there was data for years prior to that.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/d3117a9c-9731-4fdb-bde6-40f2f6ed2eff)

**Comment by jennmalcolm** [comment]
Also, we should have a consistent approach for revenue, disbursements, and production. Right now revenue and production talk about the whole period, but disbursements doesn't.

![image.png](https://images.zenhubusercontent.com/5c59c5bee180620812ea29eb/4cec17a7-6347-4f0c-a7f9-38cfc8348c5b)
![image.png](https://images.zenhubusercontent.com/5c59c5bee180620812ea29eb/3d25980d-4ef0-4278-aaa9-2f5e3b69f826)

**Comment by jennmalcolm** [comment]
On the production cards, we should not have the product capitalized. ![image.png]![image.png](https://images.zenhubusercontent.com/5c59c5bee180620812ea29eb/49e4c897-f5b6-4fd1-9cb1-823dfd19ec71)(https://images.zenhubusercontent.com/5c59c5bee180620812ea29eb/1c33d290-161f-4f2e-8259-feee27634947

We should discuss if we need the unit here. I would rather not have it to make the sentence flow better, but depending on how we deal with the geothermal (#4943), we might need it there.

**Comment by arcasarana** [comment]
@mcharg Usually, I provide fewer options but here are many.

-----------

### These show wording for no data.

**Version A.1**
Tennessee has not produced any oil (bbl) since 2003.
Note: No data exists for Tennessee prior to 2003.

**Version A.2**
Tennessee has not produced any oil (bbl) since 2003 when data was first collected.

**Version A.3**
Tennessee has not produced any oil (bbl) from 2003 to present year.

**Version A.4**
Tennessee has not produced any oil (bbl) from 2003 to __.

**Version A.5**
No oil (bbl) produced from 2003 to __.

-----------

### These show wording for consistency in talking about a range of years.

**Version B.1**
Iowa had no federal disbursements from 2005 to ___.
Iowa had no federal revenue from 2003 to __.

**Version B.2**
Iowa had no disbursements from 2005 to ___.
Iowa had no revenue from 2003 to __.

**Version B.3**
No disbursements from 2005 to __.
No revenue from 2003 to __.

**Version B.4**
Iowa did not have disbursements from (year) to (year).
Iowa did not have federal revenue from (year) to (year).

-----------
Notes:

1. Should the use of “federal” be consistent? At the moment it’s “federal revenue” and “disbursements”.
2. Versions A.5 and B.3 don’t state the year.  This is consistent with the other summary cards where there is information.  For example, the cards with data say “Trends” instead of “Oregon Trends”.  The card heading may make it clear what state is being referred to.
3. If a range of years is not chosen, then the wording can switch to “in (year)”.  For example, “Iowa had no disbursements in 2005.”

**Comment by mcharg** [comment]
1. Federal applies to both production and revenue.  We may have intentionally left it off disbursements, since we don't have land type as a field for that.
2. I could go either way on repeating the name of the state/county/offshore region.
3. You can only pick one year, but the trends always shows all the years.  This would only display if the location doesn't have data for any year.

I like the ones that say from 2003-___.  I think those are the most clear.  There was data collected in earlier years, we just don't have it available in a format we can use.

@Maroyafaied @lpgoldstein Thoughts?

**Comment by Maroyafaied** [comment]
@mcharg I like version A.4 and B.4. I'm ok with repeating the state/county/offshore region.

**Comment by arcasarana** [comment]
Ok, here's what we have.  Wording for when there's no data...

**For commodity**
(State) has not produced any (commodity) from (year) to (year).

**For data type**
(State) did not have (data type) from (year) to (year).

**Comment by mcharg** [comment]
Created #1393 to implement this change.
