### ISSUE TITLE
Consider adding selected commodity to cards and charts to make clear what data is showing

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#751]
Since we are now applying a commodity selection to the whole page, we might need to test/consider whether we need to add a commodity label to the cards and elsewhere to make it clear what they are showing. To me, I think the summary cards would be a source of confusion especially since we are still leaving the top commodities there. Should we add the product label somewhere in the top part to make it clear that the top numbers are only for the selected product(s).

![image.png](https://images.zenhubusercontent.com/5c59c5bee180620812ea29eb/1b38c35e-6367-4a2d-b9cb-1aec0623e0ee)

**Comment by mcharg** [comment]
Also need to consider selected disposition for production.

**Comment by arcasarana** [comment]
Ok, here's take 2.  I think it reads a bit clearer with subheaders and making sure the content underneath thematically fits that subheader.  The subheaders also helps to create a visual separation of the content that I think the cards need.

Feedback?

<img width="513" alt="Screen Shot 2021-02-27 at 7 38 53 PM" src="https://user-images.githubusercontent.com/36823491/109404401-b44a6700-7933-11eb-8ed3-679c5db17cf8.png">

**Comment by mcharg** [comment]
@arcasarana I like it.  @jlouis-onrr Thoughts on how difficult this would be to implement?

**Comment by mcharg** [comment]
@Maroyafaied @lpgoldstein Thoughts?

**Comment by Maroyafaied** [comment]
@mcharg I think it's good to clarify that the trend and year total is showing selected commodity or commodities but we don't need the second label since we currently list how many commodities there are total so it's clear we're showing top 3 .  I would also reword the first label to " Trend and data shown are for selected commodities"

![image](https://user-images.githubusercontent.com/40175688/109530496-04c8de00-7a74-11eb-8e35-bdc4c1636cd1.png)
![image](https://user-images.githubusercontent.com/40175688/109530546-101c0980-7a74-11eb-9f90-9c2341c45227.png)

**Comment by arcasarana** [comment]
Ok, here's the updated version.  Took out the 2nd label and reworded the first label.

<img width="253" alt="Screen Shot 2021-03-03 at 1 20 29 PM" src="https://user-images.githubusercontent.com/36823491/109853001-69766b00-7c23-11eb-805f-098a23dc66ea.png">
<img width="269" alt="Screen Shot 2021-03-03 at 1 19 58 PM" src="https://user-images.githubusercontent.com/36823491/109853017-6da28880-7c23-11eb-99ac-5ea4bec040e9.png">

**Comment by mcharg** [comment]
I'll put this in the OGOR B prototype, so we can get user feedback.
