### ISSUE TITLE
Add more context around Great American Outdoors Act

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#919]
Aside from LWCF funding, the Great American Outdoors Act specifies that 50% (up to $1.9B) now going to General Treasury from energy development will be going to the National Parks and Public Land Legacy Restoration Fund starting in FY21.

We should consider adding more context around this law in How revenues work/disbursements.

![image](https://user-images.githubusercontent.com/30806839/91901557-a0ac9500-ec5d-11ea-98ea-27bacde7f516.png)

Here's the link to the Act:

https://www.congress.gov/bill/116th-congress/house-bill/1957

**Comment by lpgoldstein** [comment]
https://revenuedata.doi.gov/how-revenue-works/lwcf

**Comment by devynpowell** [comment]
[Disbursements-DP-092520.docx](https://github.com/ONRR/nrrd/files/5285406/Disbursements-DP-092520.docx)

Attaching document with suggested edits to disbursements page. In this draft, I've added a bullet point describing the new fund (National Park and Public Lands Legacy Restoration Fund) established by the GAOA, and added a note to the LWCF bullet noting that the passage of the GAOA assures full funding of that fund. 

Questions/notes:
* not sure if the GAOA note on the LWCF bullet belongs on this page, or the information on the LWCF page is enough.
* there isn't yet a separate page for the NPPLLRF (what an acronym!), and assuming it's still too new to make one, but let me know if that's something we want to get started on!
* I didn't create a separate section for relevant laws (one thing we had discussed, Lindsay) - but happy to do that as well; if we go that route, I'd imagine we'd want to include context about other legislation in addition to the GAOA, and would want some guidance on whether disbursements page is the right spot for that. Let me know.
* Otherwise, let me know how this looks!

**Comment by lpgoldstein** [comment]
@devynpowell This looks great! Writing clear and concise and the addition doesn't bulk up the page at all. Let's have @Maroyafaied review, then we will have @jennmalcolm review, then I can show you how to make the actual change to the page. We can talk to Jennifer about starting the separate page for NPPLLRF, but I think it's a good idea to at least draft while the information is still fresh to you and then we can take live later.

**Comment by devynpowell** [comment]
Sounds good! Keep me posted, and I will start drafting some copy about the NPPLLRF from my GAOA notes.

**Comment by Maroyafaied** [comment]
Should this be $1.9 billion each year not $9 billion? I might be wrong so I'll pass it to @jennmalcolm for review. 
![image](https://user-images.githubusercontent.com/40175688/94479504-20ad1880-0192-11eb-9dbc-06750a052981.png)

**Comment by lpgoldstein** [comment]
@Maroyafaied good find

**Comment by devynpowell** [comment]
You're right, @Maroyafaied! That was a typo on my part, apologies - thanks for catching! It's ~$9 billion *TOTAL* over 5 years, but $1.9B *annually.*

**Comment by jennmalcolm** [comment]
I checked with our disbursements team, and I guess it's still up in the air if ONRR will disburse to the new fund or Treasury will move the funds at the end of the year. So, I guess we shouldn't add it to the section about the 6 funds we disburse to until the process is determined. It may be its own fund, or we may need to mention it under the General Treasury--depending how it will be done. I would like to add some context no matter what process will be used. I do think it would be appropriate to create a new page for National Parks and Public Land Legacy Restoration Fund, and we could draft something based on what the Act tells us about where the money comes from and what it will be used for.

**Comment by devynpowell** [comment]
[Disbursements-DP-100220.docx](https://github.com/ONRR/nrrd/files/5341300/Disbursements-DP-100220.docx)

I realized I hadn't uploaded this - here's the correction to the disbursements page language (now says $1.9 billion each year through 2025).
